<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { BellOff, Check, ChevronLeft, ChevronRight, Clock3, ExternalLink, RefreshCw, Trash2, XCircle } from 'lucide-vue-next'
import { request } from '../api'
import type { Delivery, PageResult } from '../types'

const route=useRoute(),router=useRouter(),result=ref<PageResult<Delivery>|null>(null),loading=ref(true),error=ref(''),removing=ref<number|null>(null)
const pages=computed(()=>{const total=result.value?.totalPages||0,current=result.value?.page||1,start=Math.max(1,Math.min(current-2,total-4)),end=Math.min(total,start+4);return Array.from({length:Math.max(0,end-start+1)},(_,index)=>start+index)})
function routePage(value:unknown){const page=Number(value);return Number.isInteger(page)&&page>0?page:1}
async function load(target?:number,syncURL=true){const page=target||routePage(route.query.page);loading.value=true;error.value='';try{const value=await request<PageResult<Delivery>>(`/deliveries?page=${page}`);if(value.totalPages&&page>value.totalPages){await load(value.totalPages,syncURL);return}result.value=value;if(syncURL)await router.replace({query:page>1?{page:String(page)}:{}})}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function remove(item:Delivery){if(!confirm(`取消“${item.videoTitle}”的等待发送通知？`))return;removing.value=item.id;error.value='';try{await request(`/deliveries/${item.id}`,{method:'DELETE'});const target=(result.value?.items.length===1&&(result.value?.page||1)>1)?(result.value!.page-1):result.value?.page;await load(target)}catch(e){error.value=e instanceof Error?e.message:'取消发送失败';await load(result.value?.page)}finally{removing.value=null}}
function date(value:number){return new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(value*1000)}
const status={sent:{label:'已送达',icon:Check},pending:{label:'等待发送',icon:Clock3},failed:{label:'发送失败',icon:XCircle}}
onMounted(()=>load())
watch(()=>route.query.page,value=>{const page=routePage(value);if(page!==result.value?.page)void load(page,false)})
</script>

<template><section class="page"><header class="page-header"><div><p class="eyebrow">投递记录</p><h1>通知</h1><p>共 {{result?.total||0}} 条</p></div><button class="icon-button" title="刷新" @click="load(result?.page)"><RefreshCw :size="19"/></button></header><p v-if="error" class="alert error">{{error}}</p><div v-if="loading" class="loading-state"><span class="spinner"/>正在加载</div><div v-else-if="!result?.items.length" class="empty-state"><BellOff :size="34"/><h2>还没有通知</h2></div><template v-else><div class="history-list"><article v-for="item in result.items" :key="item.id" class="history-row"><img :src="item.creatorAvatar" alt="" class="avatar small"/><a :href="item.videoUrl" target="_blank" rel="noreferrer" class="history-main"><div><strong>{{item.creatorName}}</strong><span class="delivery-status" :class="item.status"><component :is="status[item.status].icon" :size="14"/>{{status[item.status].label}}</span></div><p>{{item.videoTitle}}</p><small>{{date(item.createdAt)}}<span v-if="item.error"> · {{item.error}}</span></small></a><div class="history-actions"><a :href="item.videoUrl" target="_blank" rel="noreferrer" class="icon-button compact" title="打开视频"><ExternalLink :size="17"/></a><button v-if="item.status==='pending'" class="icon-button compact danger-button" title="取消发送" :disabled="removing===item.id" @click="remove(item)"><Trash2 :size="17"/></button></div></article></div><nav v-if="result.totalPages>1" class="pager" aria-label="投递记录分页"><button class="icon-button compact" title="上一页" :disabled="result.page<=1" @click="load(result.page-1)"><ChevronLeft :size="18"/></button><button v-for="page in pages" :key="page" class="page-number" :class="{active:page===result.page}" :aria-current="page===result.page?'page':undefined" @click="load(page)">{{page}}</button><button class="icon-button compact" title="下一页" :disabled="result.page>=result.totalPages" @click="load(result.page+1)"><ChevronRight :size="18"/></button></nav></template></section></template>
